#У даному файлі створений графічний інтерфейс
#Для подальшої розробки застосунку я імпортую його частину в клієнт "GreenData_client"
#Відокремив графічний інтерфейс в інший файл для того щоб при змінах в ньому не треба було вносити зміни в клієнт

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow():

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(947, 458)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 40, 491, 291))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(26, 10, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Padauk Book [PYRS]")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(270, 340, 171, 27))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 340, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Garuda")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 380, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Garuda")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 400, 381, 27))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(410, 400, 101, 27))
        font = QtGui.QFont()
        font.setFamily("Garuda")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 340, 61, 27))
        font = QtGui.QFont()
        font.setFamily("Garuda")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(570, 10, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Padauk Book [PYRS]")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(560, 40, 371, 192))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(677, 238, 253, 27))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(560, 242, 117, 17))
        font = QtGui.QFont()
        font.setFamily("Garuda")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(560, 272, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Garuda")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(677, 270, 111, 27))
        self.textEdit_4.setObjectName("textEdit_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(798, 270, 132, 27))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(560, 320, 108, 17))
        font = QtGui.QFont()
        font.setFamily("Garuda")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(678, 315, 109, 27))
        self.textEdit_5.setObjectName("textEdit_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(799, 313, 130, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(560, 360, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Garuda")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(599, 354, 111, 27))
        self.textEdit_6.setObjectName("textEdit_6")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(560, 390, 171, 17))
        font = QtGui.QFont()
        font.setFamily("Garuda")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(560, 420, 291, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(744, 385, 99, 27))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GreenData"))
        self.label.setText(_translate("MainWindow", "Статистика посівів"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Введіть рік..."))
        self.label_2.setText(_translate("MainWindow", "Отримати статистику за рік:"))
        self.label_3.setText(_translate("MainWindow", "Додати посів:"))
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", "Введіть данні посіву..."))
        self.pushButton.setText(_translate("MainWindow", "Додати"))
        self.pushButton_2.setText(_translate("MainWindow", "Знайти"))
        self.label_4.setText(_translate("MainWindow", "Облік витрат та доходів"))
        self.label_5.setText(_translate("MainWindow", "Об\'єкт витрат:"))
        self.label_6.setText(_translate("MainWindow", "Сума витрати:"))
        self.textEdit_4.setPlaceholderText(_translate("MainWindow", "Введіть суму.."))
        self.pushButton_3.setText(_translate("MainWindow", "Додати"))
        self.label_7.setText(_translate("MainWindow", "Сума доходу:"))
        self.textEdit_5.setPlaceholderText(_translate("MainWindow", "Введіть суму.."))
        self.pushButton_4.setText(_translate("MainWindow", "Додати "))
        self.label_8.setText(_translate("MainWindow", "Рік:"))
        self.textEdit_6.setPlaceholderText(_translate("MainWindow", "Введіть рік..."))
        self.label_9.setText(_translate("MainWindow", "Дохід за вказаний рік:"))
        self.pushButton_5.setText(_translate("MainWindow", "Розрахувати"))
